# Generated by Django 3.0.7 on 2020-08-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200823_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='dine_in',
        ),
    ]
