# Generated by Django 3.0.7 on 2020-08-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200825_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dine_in',
        ),
    ]
