# Generated by Django 3.0.7 on 2020-08-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_dine_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dine',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
